export const GET_BILL_LIST_REQUEST = 'GET_BILL_LIST_REQUEST';
export const GET_BILL_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_BILL_LIST_FAIL = 'GET_BILL_LIST_FAIL';

export const DELETE_BILL_REQUEST = 'DELETE_BILL_REQUEST';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
export const DELETE_BILL_FAIL = 'DELETE_BILL_FAIL';
export const RESET_BILL_LIST = 'RESET_BILL_LIST';

export const UPDATE_BILL_REQUEST = 'UPDATE_BILL_REQUEST'
export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS'
export const UPDATE_BILL_FAIL = 'UPDATE_BILL_FAIL'

export const ADD_BILL_REQUEST = 'ADD_BILL_REQUEST'
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS'
export const ADD_BILL_FAIL = 'ADD_BILL_FAIL'

export const SET_IS_EXIST_BILL_MODIFIED = 'SET_IS_EXIST_BILL_MODIFIED'

export const GET_INFO_BILL_REQUEST = 'GET_INFO_BILL_REQUEST'
export const GET_INFO_BILL_SUCCESS = 'GET_INFO_BILL_SUCCESS'
export const GET_INFO_BILL_FAIL = 'GET_INFO_BILL_FAIL'


export const GET_BILL_LIST_REQUEST_USER = 'GET_BILL_LIST_REQUEST_USER';
export const GET_BILL_LIST_SUCCESS_USER = 'GET_EVENT_LIST_SUCCESS_USER';
export const GET_BILL_LIST_FAIL_USER = 'GET_BILL_LIST_FAIL_USER';


export const GET_BILL_LIST_REQUEST_USER_DTT = 'GET_BILL_LIST_REQUEST_USER_DTT';
export const GET_BILL_LIST_SUCCESS_USER_DTT = 'GET_BILL_LIST_SUCCESS_USER_DTT';
export const GET_BILL_LIST_FAIL_USER_DTT = 'GET_BILL_LIST_FAIL_USER_DTT';