export const GET_LISTCATE_REQUEST = "GET_LISTCATE_REQUEST"
export const GET_LISTCATE_SUCCESS = "GET_LISTCATE_SUCCESS"
export const GET_LISTCATE_FAIL = "GET_LISTCATE_FAIL"

export const POST_ADDCATE_REQUEST = "POST_ADDCATE_REQUEST "
export const POST_ADDCATE_SUCCESS = "POST_ADDCATE_SUCCESS"
export const POST_ADDCATE_FAIL = "POST_ADDCATE_FAIL"
