export const GET_EVENT_LIST_REQUEST = 'GET_EVENT_LIST_REQUEST';
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_EVENT_LIST_FAIL = 'GET_EVENT_LIST_FAIL';

export const GET_EVENT_DETAIL_REQUEST = 'GET_EVENT_DETAIL_REQUEST';
export const GET_EVENT_DETAIL_SUCCESS = 'GET_EVENT_DETAIL_SUCCESS';
export const GET_EVENT_DETAIL_FAIL = 'GET_EVENT_DETAIL_FAIL';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';
export const RESET_EVENT_LIST = 'RESET_EVENT_LIST';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL'

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL'

export const SET_IS_EXIST_EVENT_MODIFIED = 'SET_IS_EXIST_EVENT_MODIFIED'

export const GET_INFO_EVENT_REQUEST = 'GET_INFO_EVENT_REQUEST'
export const GET_INFO_EVENT_SUCCESS = 'GET_INFO_EVENT_SUCCESS'
export const GET_INFO_EVENT_FAIL = 'GET_INFO_EVENT_FAIL'