export const GET_LISTLIKE_REQUEST = "GET_LISTLIKE_REQUEST"
export const GET_LISTLIKE_SUCCESS = "GET_LISTLIKE_SUCCESS"
export const GET_LISTLIKE_FAIL = "GET_LISTLIKE_FAIL"

export const GET_LISTCOMMENT_REQUEST = "GET_LISTCOMMENT_REQUEST"
export const GET_LISTCOMMENT_SUCCESS = "GET_LISTCOMMENT_SUCCESS"
export const GET_LISTCOMMENT_FAIL = "GET_LISTCOMMENT_FAIL"

export const POST_LIKEUNLIKE_REQUEST = "POST_LIKEUNLIKE_REQUEST"
export const POST_LIKEUNLIKE_SUCCESS = "POST_LIKEUNLIKE_SUCCESS"
export const POST_LIKEUNLIKE_FAIL = "POST_LIKEUNLIKE_FAIL"

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL"

export const GET_LIKECHECK_REQUEST = "GET_LIKECHECK_REQUEST"
export const GET_LIKECHECK_SUCCESS = "GET_LIKECHECK_SUCCESS"
export const GET_LIKECHECK_FAIL = "GET_LIKECHECK_FAIL"

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_FAIL = "POST_DELETE_FAIL"