export const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";

export const GET_MOVIE_HETHONG_LIST_REQUEST = "GET_MOVIE_HETHONG_LIST_REQUEST";
export const GET_MOVIE_HETHONG_LIST_SUCCESS = "GET_MOVIE_HETHONG_LIST_SUCCESS";
export const GET_MOVIE_HETHONG_LIST_FAIL = "GET_MOVIE_HETHONG_LIST_FAIL";

export const GET_MOVIE_LIST_SAP_REQUEST = "GET_MOVIE_LIST_SAP_REQUEST";
export const GET_MOVIE_LIST_SAP_SUCCESS = "GET_MOVIE_LIST_SAP_SUCCESS";
export const GET_MOVIE_LIST_SAP_FAIL = "GET_MOVIE_LIST_SAP_FAIL";

export const GET_MOVIE_LISTBYDAY_REQUEST = "GET_MOVIE_LISTBYDAY_REQUEST";
export const GET_MOVIE_LISTBYDAY_SUCCESS = "GET_MOVIE_LISTBYDAY_SUCCESS";
export const GET_MOVIE_LISTBYDAY_FAIL = "GET_MOVIE_LISTBYDAY_FAIL";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const RESET_MOVIE_MANAGEMENT = "RESET_MOVIE_MANAGEMENT";

export const POST_UPDATE_MOVIE_REQUEST = "POST_UPDATE_MOVIE_REQUEST";
export const POST_UPDATE_MOVIE_SUCCESS = "POST_UPDATE_MOVIE_SUCCESS";
export const POST_UPDATE_MOVIE_FAIL = "POST_UPDATE_MOVIE_FAIL";

export const UPDATE_NONEIMAGE_MOVIE_REQUEST = "UPDATE_NONEIMAGE_MOVIE_REQUEST";
export const UPDATE_NONEIMAGE_MOVIE_SUCCESS = "UPDATE_NONEIMAGE_MOVIE_SUCCESS";
export const UPDATE_NONEIMAGE_MOVIE_FAIL = "UPDATE_NONEIMAGE_MOVIE_FAIL";

export const GET_MOVIE_LIST_REQUEST2 = "GET_MOVIE_LIST_REQUEST2";
export const GET_MOVIE_LIST_SUCCESS2 = "GET_MOVIE_LIST_SUCCESS2";
export const GET_MOVIE_LIST_FAIL2 = "GET_MOVIE_LIST_FAIL2";

export const GET_SCHEDULE_LIST_REQUEST2 = "GET_SCHEDULE_LIST_REQUEST2";
export const GET_SCHEDULE_LIST_SUCCESS2 = "GET_SCHEDULE_LIST_SUCCESS2";
export const GET_SCHEDULE_LIST_FAIL2 = "GET_SCHEDULE_LIST_FAIL2";

export const DELETE_SCHEDULE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_SCHEDULE_FAIL = "DELETE_MOVIE_FAIL";

export const ADD_MOVIE_UPLOAD_REQUEST = "ADD_MOVIE_UPLOAD_REQUEST";
export const ADD_MOVIE_UPLOAD_SUCCESS = "ADD_MOVIE_UPLOAD_SUCCESS";
export const ADD_MOVIE_UPLOAD_FAIL = "ADD_MOVIE_UPLOAD_FAIL";

//SCHEDULE
export const RESET_SCHEDULE_MANAGEMENT = "RESET_SCHEDULE_MANAGEMENT";

export const POST_UPDATE_SCHEDULE_REQUEST = "POST_UPDATE_SCHEDULE_REQUEST";
export const POST_UPDATE_SCHEDULE_SUCCESS = "POST_UPDATE_SCHEDULE_SUCCESS";
export const POST_UPDATE_SCHEDULE_FAIL = "POST_UPDATE_SCHEDULE_FAIL";

export const UPDATE_NONEIMAGE_SCHEDULE_REQUEST = "UPDATE_NONEIMAGE_SCHEDULE_REQUEST";
export const UPDATE_NONEIMAGE_SCHEDULE_SUCCESS = "UPDATE_NONEIMAGE_SCHEDULE_SUCCESS";
export const UPDATE_NONEIMAGE_SCHEDULE_FAIL = "UPDATE_NONEIMAGE_SCHEDULE_FAIL";

export const ADD_SCHEDULE_UPLOAD_REQUEST = "ADD_SCHEDULE_UPLOAD_REQUEST";
export const ADD_SCHEDULE_UPLOAD_SUCCESS = "ADD_SCHEDULE_UPLOAD_SUCCESS";
export const ADD_SCHEDULE_UPLOAD_FAIL = "ADD_SCHEDULE_UPLOAD_FAIL";

export const SAVE_BEFOREINSTALLPROMPT_EVENT = "SAVE_BEFOREINSTALLPROMPT_EVENT"; // Lưu lại event beforeinstallprompt để hiện lại màn hình install pwa khi cần
