export const GET_REVIEW_LIST_REQUEST = 'GET_REVIEW_LIST_REQUEST';
export const GET_REVIEW_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_REVIEW_LIST_FAIL = 'GET_REVIEW_LIST_FAIL';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const RESET_REVIEW_LIST = 'RESET_REVIEW_LIST';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST'
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS'
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL'

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'

export const SET_IS_EXIST_REVIEW_MODIFIED = 'SET_IS_EXIST_REVIEW_MODIFIED'

export const GET_INFO_REVIEW_REQUEST = 'GET_INFO_REVIEW_REQUEST'
export const GET_INFO_REVIEW_SUCCESS = 'GET_INFO_REVIEW_SUCCESS'
export const GET_INFO_REVIEW_FAIL = 'GET_INFO_REVIEW_FAIL'