export const GET_TICKET_REQUEST = "GET_TICKET_REQUEST"
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS"
export const GET_TICKET_FAIL = "GET_TICKET_FAIL"

export const GET_ALLTICKET_REQUEST = "GET_ALLTICKET_REQUEST"
export const GET_ALLTICKET_SUCCESS = "GET_ALLTICKET_SUCCESS"
export const GET_ALLTICKET_FAIL = "GET_ALLTICKET_FAIL"